<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerusahaanSeeder extends Seeder
{
    public function run()
    {
        DB::table('perusahaan')->insert([
            [
                'pengguna_id' => 3,
                'deskripsi' => 'Menyediakan solusi baja yang kuat dan tahan lama untuk kebutuhan industri.',
                'visi' => 'Menjadi pemimpin dalam industri baja dengan solusi yang berkelanjutan.',
                'misi' => 'Memproduksi produk baja berkualitas tinggi untuk mendukung perkembangan infrastruktur.',
                'layanan' => 'Fabrikasi baja, pengolahan logam, konstruksi industri',
                'npwp' => '01.234.567.8-912.345',
                'akta_pendirian' => 'No. 123/BTSW/2010',
                'izin_operasional' => 'No. 456/BTSW/2011',
                'sertifikasi_bnsp' => 'No. 789/BNSP/2015',
                'file_npwp' => 'npwp_3.pdf',
                'file_akta_pendirian' => 'akta_3.pdf',
                'file_izin_operasional' => 'izin_3.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_3.pdf',
            ],
            [
                'pengguna_id' => 4,
                'deskripsi' => 'Membangun struktur kokoh untuk masa depan yang lebih baik.',
                'visi' => 'Menjadi perusahaan baja yang mengedepankan kualitas dan keselamatan.',
                'misi' => 'Memberikan konstruksi baja yang tahan lama dan berkualitas untuk proyek besar.',
                'layanan' => 'Penyediaan baja struktural, perancangan dan pembangunan infrastruktur',
                'npwp' => '02.345.678.9-123.456',
                'akta_pendirian' => 'No. 124/MBU/2012',
                'izin_operasional' => 'No. 457/MBU/2013',
                'sertifikasi_bnsp' => 'No. 790/BNSP/2016',
                'file_npwp' => 'npwp_4.pdf',
                'file_akta_pendirian' => 'akta_4.pdf',
                'file_izin_operasional' => 'izin_4.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_4.pdf',
            ],
            [
                'pengguna_id' => 5,
                'deskripsi' => 'Fabrikasi baja dengan kualitas tinggi untuk setiap proyek besar.',
                'visi' => 'Menjadi pilihan utama dalam fabrikasi baja di Indonesia.',
                'misi' => 'Menghasilkan produk baja yang sesuai dengan kebutuhan klien secara efisien dan efektif.',
                'layanan' => 'Pembuatan struktur baja, pengelasan, pengolahan material',
                'npwp' => '03.456.789.0-234.567',
                'akta_pendirian' => 'No. 125/FAP/2015',
                'izin_operasional' => 'No. 458/FAP/2016',
                'sertifikasi_bnsp' => 'No. 791/BNSP/2018',
                'file_npwp' => 'npwp_5.pdf',
                'file_akta_pendirian' => 'akta_5.pdf',
                'file_izin_operasional' => 'izin_5.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_5.pdf',
            ],
            [
                'pengguna_id' => 6,
                'deskripsi' => 'Fabrikasi baja dengan teknologi canggih dan bahan terbaik.',
                'visi' => 'Menjadi pemimpin dalam fabrikasi baja dan teknik konstruksi di Asia Tenggara.',
                'misi' => 'Memberikan solusi baja yang berkualitas dengan inovasi terbaru.',
                'layanan' => 'Konstruksi baja, desain struktur, pengolahan logam',
                'npwp' => '04.567.890.1-345.678',
                'akta_pendirian' => 'No. 126/GF/2017',
                'izin_operasional' => 'No. 459/GF/2017',
                'sertifikasi_bnsp' => 'No. 792/BNSP/2019',
                'file_npwp' => 'npwp_6.pdf',
                'file_akta_pendirian' => 'akta_6.pdf',
                'file_izin_operasional' => 'izin_6.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_6.pdf',
            ],
            [
                'pengguna_id' => 7,
                'deskripsi' => 'Mengutamakan kekuatan dan ketahanan dalam setiap produk baja.',
                'visi' => 'Memproduksi baja berkualitas tinggi untuk pembangunan yang lebih kokoh.',
                'misi' => 'Menjadi mitra terpercaya dalam pembuatan dan penyediaan baja.',
                'layanan' => 'Penyedia baja struktural, fabrikasi dan konstruksi baja',
                'npwp' => '05.678.901.2-456.789',
                'akta_pendirian' => 'No. 127/LB/2018',
                'izin_operasional' => 'No. 460/LB/2018',
                'sertifikasi_bnsp' => 'No. 793/BNSP/2020',
                'file_npwp' => 'npwp_7.pdf',
                'file_akta_pendirian' => 'akta_7.pdf',
                'file_izin_operasional' => 'izin_7.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_7.pdf',
            ],
            [
                'pengguna_id' => 8,
                'deskripsi' => 'Menciptakan struktur baja yang solid dan berdaya guna tinggi.',
                'visi' => 'Menjadi penyedia baja terbaik dengan standar kualitas internasional.',
                'misi' => 'Membangun produk baja yang dapat diandalkan untuk berbagai keperluan konstruksi.',
                'layanan' => 'Penyediaan baja, fabrikasi struktural, konstruksi baja',
                'npwp' => '06.789.012.3-567.890',
                'akta_pendirian' => 'No. 128/Bengkong/2019',
                'izin_operasional' => 'No. 461/Bengkong/2019',
                'sertifikasi_bnsp' => 'No. 794/BNSP/2021',
                'file_npwp' => 'npwp_8.pdf',
                'file_akta_pendirian' => 'akta_8.pdf',
                'file_izin_operasional' => 'izin_8.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_8.pdf',
            ],
            [
                'pengguna_id' => 9,
                'deskripsi' => 'Menjadi mitra terbaik dalam setiap proyek metalurgi dan fabrikasi.',
                'visi' => 'Memberikan produk baja yang memiliki standar tinggi di seluruh dunia.',
                'misi' => 'Menghasilkan baja dengan ketepatan dan ketahanan yang luar biasa.',
                'layanan' => 'Fabrikasi baja, desain struktural, konstruksi industri',
                'npwp' => '07.890.123.4-678.901',
                'akta_pendirian' => 'No. 129/NMW/2020',
                'izin_operasional' => 'No. 462/NMW/2020',
                'sertifikasi_bnsp' => 'No. 795/BNSP/2022',
                'file_npwp' => 'npwp_9.pdf',
                'file_akta_pendirian' => 'akta_9.pdf',
                'file_izin_operasional' => 'izin_9.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_9.pdf',
            ],
            [
                'pengguna_id' => 10,
                'deskripsi' => 'Teknologi fabrikasi terbaru untuk memenuhi tuntutan industri modern.',
                'visi' => 'Menjadi inovator utama dalam fabrikasi dan konstruksi baja.',
                'misi' => 'Memberikan solusi fabrikasi yang berorientasi pada teknologi terbaru.',
                'layanan' => 'Fabrikasi baja, konstruksi baja, desain teknik',
                'npwp' => '08.901.234.5-789.012',
                'akta_pendirian' => 'No. 130/BFT/2021',
                'izin_operasional' => 'No. 463/BFT/2021',
                'sertifikasi_bnsp' => 'No. 796/BNSP/2023',
                'file_npwp' => 'npwp_10.pdf',
                'file_akta_pendirian' => 'akta_10.pdf',
                'file_izin_operasional' => 'izin_10.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_10.pdf',
            ],
            [
                'pengguna_id' => 11,
                'deskripsi' => 'Perusahaan konstruksi baja terkemuka yang menyediakan solusi global.',
                'visi' => 'Menjadi penyedia baja terbaik dengan teknologi mutakhir di seluruh dunia.',
                'misi' => 'Menawarkan layanan konstruksi baja yang inovatif dan tahan lama.',
                'layanan' => 'Konstruksi baja, perencanaan struktural, fabrikasi logam',
                'npwp' => '09.012.345.6-890.123',
                'akta_pendirian' => 'No. 131/PC/2022',
                'izin_operasional' => 'No. 464/PC/2022',
                'sertifikasi_bnsp' => 'No. 797/BNSP/2024',
                'file_npwp' => 'npwp_11.pdf',
                'file_akta_pendirian' => 'akta_11.pdf',
                'file_izin_operasional' => 'izin_11.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_11.pdf',
            ],
            [
                'pengguna_id' => 12,
                'deskripsi' => 'Penyedia solusi baja terkemuka dengan pengalaman lebih dari 20 tahun.',
                'visi' => 'Menjadi pilihan utama untuk segala kebutuhan fabrikasi baja berkualitas tinggi.',
                'misi' => 'Menghasilkan produk baja yang tahan lama dan sesuai dengan kebutuhan pasar.',
                'layanan' => 'Fabrikasi baja, konstruksi industri, pengolahan logam',
                'npwp' => '10.123.456.7-901.234',
                'akta_pendirian' => 'No. 132/PS/2023',
                'izin_operasional' => 'No. 465/PS/2023',
                'sertifikasi_bnsp' => 'No. 798/BNSP/2025',
                'file_npwp' => 'npwp_12.pdf',
                'file_akta_pendirian' => 'akta_12.pdf',
                'file_izin_operasional' => 'izin_12.pdf',
                'file_sertifikasi_bnsp' => 'bnsp_12.pdf',
            ],
        ]);
    }
}
